
REPO=jorgeacf/kafka

.PHONY: all
all:
	make build

.PHONY: build
build:
	docker build -t $(REPO):latest .

.PHONY: nocache
nocache:
	docker build -t $(REPO):latest --no-cache .

.PHONY: run
run:
	docker run -ti -p 2181:2181 -p 9092:9092 $(REPO):latest